services:
  mongo:
    image: mongo:6
    container_name: esp32mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: esp32api
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://root:password@mongo:27017/esp32db?authSource=admin
      CORS_ORIGIN: "*"
    depends_on:
      - mongo

  display:
    build: ./display
    container_name: esp32display
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  mongo_data:
